---
- name: Pull docker image of covid_control_system
  hosts: all
  tasks:
    - name: Pull frontend image
      docker_image:
        name: nishantchhattani/covid_control_frontend
        source: pull
        
    - name: Pull Backend image
      docker_image:
        name: nishantchhattani/covid_control_backend
        source: pull
